### ISSUE TITLE
Can't run animation again

### ISSUE THREAD

**Issue by Huddie** [Dywane/DWAnimatedLabel#2]
I'm trying to use this label as an instructions label where I display the text (with the animation)
Then change the text and do that again.. and again... 

Works the first time but the second time nothing shows

**Comment by Dywane** [comment]
OK, this is my lack of consideration , I will fix this

**Comment by Huddie** [comment]
Thanks! This is a cool pod

**Comment by Dywane** [comment]
Already fix this, later I will refactor the `DWAnimator` in order to add more animation(disappear animation maybe) and provide customization
